### ISSUE TITLE
Create LogIn Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [Kumar-laxmi/SmartChat#1]
LogIn page is required so that when user opens up the website, then he is asked to authenticate first.

**Comment by RohithBoppey** [comment]
Can I work on this? Please assign this to me. I would like to work on this.

**Comment by Kumar-laxmi** [comment]
> Can I work on this? Please assign this to me. I would like to work on this.

@RohithBoppey Thank you for your interest, maybe next time I will assign an issue.
